### ISSUE TITLE
Forks of this repo

### ISSUE THREAD

**Issue by mbrowne** [mbrowne/babel-plugin-pure-static-props#3]
Hi @ammmze,
Following up on our discussion at https://github.com/styled-components/babel-plugin-styled-components/issues/245, I just wanted to let you know that someone else recently forked this repo as well, and added some tests:
https://github.com/Mattgic/babel-plugin-pure-static-props

...just in case that's a helpful starting point for you.

**Comment by ammmze** [comment]
Thanks! I'll look through that and see if there's more needed above what i've put in the PR I just created!

**Comment by mryechkin** [comment]
Glad to see this is getting more attention - this plugin was super helpful in fixing tree-shaking issues in a React component library I'm working on. As I saw you mention in that thread @mbrowne - would love to see this get un-deprecated 👍🏻

**Comment by mbrowne** [comment]
Closing since this PR will be merged soon:
https://github.com/mbrowne/babel-plugin-pure-static-props/pull/4
